# Site settings
theme: jekyll-theme-primer
# This title is default fallback. It will only be used for the <title> tag if a particular page does not have a title specified in its front matter.Mail Automated Process_GAS to automate mail processing
title: 'b'
description: 'f'
